name: helloWorld
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
      node:
        image: node:latest
      golang:
        image: golang:latest
#    container:
#      image: golang:1.18
    steps:

      - uses: actions/checkout@v3

#      - name: Build
#        run: go build -v ./...

      - name: Test
        run: go test -v ./...
