name: helloWorld
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: golang_project
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      golang:
        image: golang:latest
    steps:
      - uses: actions/checkout@v3

#      - name: Build
#        run: go build -v ./...
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          which migrate
      - name: Build
        run: go build -v ./...
      - name: Run migrations
        run: make migrate-up
      - name: Test
        run: go test -v ./...

  create-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SECRET }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: echo ${{ secrets.GCP_PROJECT }}
      - name: Add SSH Key To Runner
        env:
          SSH_PUBLIC: ${{secrets.SSH_PUBLIC}}
          SSH_PRIVATE: ${{secrets.SSH_PRIVATE}}
          HOST_SSH: ${{ secrets.HOST_SSH }}
        run: rm -rf .ssh && mkdir ~/.ssh && cd ~/.ssh && ls && echo $SSH_PUBLIC > id_rsa.pub && echo "${{secrets.SSH_PRIVATE}}" > id_rsa && echo $HOST_SSH > known_hosts && chmod 400 ~/.ssh/id_rsa
      - name: Check Projects List
        run: gcloud projects list
      - name: Connect to Time Tracker
        run: ssh -tt sanjay@35.200.199.253
      - name: Check Ruby Version
        run: ruby -v

