name: helloWorld
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: golang_project
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      golang:
        image: golang:latest
#    container:
#      image: golang:1.18
    steps:

      - uses: actions/checkout@v3
#      - name: Install Golang-Migrate
#        run: brew install golang-migrate

#      - name: Build
#        run: go build -v ./...
      - name: Create Table Users
        run: make migrate-up
      - name: Test
        run: go test -v ./...

#      - name: Create Database
#        run: make create-database
#      - name: Setup Database
#        run: psql -h localhost -U postgres password=postgres -c 'CREATE DATABASE "postgres_dk";'
#
#      - name: Connect to database and create table
#        run: psql -h localhost -U postgres password=postgres -c 'CREATE TABLE users ( name varchar );'
