name: helloWorld
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: golang_project
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      golang:
        image: golang:latest
#    container:
#      image: golang:1.18
    steps:
      - uses: actions/checkout@v3
#      - uses: golang-migrate/migrate@v4
#      - name: Install Golang-Migrate
#        run: brew install golang-migrate

#      - name: Build
#        run: go build -v ./...
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          which migrate
      - name: Build
        run: go build -v ./...
      - name: Run migrations
        run: make migrate-up
      - name: Test
        run: go test -v ./...

  create-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SECRET }}
          export_default_credentials: true
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
#      - name: Create Database
#        run: make create-database
#      - name: Setup Database
#        run: psql -h localhost -U postgres password=postgres -c 'CREATE DATABASE "postgres_dk";'
#
#      - name: Connect to database and create table
#        run: psql -h localhost -U postgres password=postgres -c 'CREATE TABLE users ( name varchar );'
