name: helloWorld
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      golang:
        image: golang:latest
#    container:
#      image: golang:1.18
    steps:

      - uses: actions/checkout@v3

#      - name: Build
#        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Setup Database
        run: psql -h localhost -U postgres password=postgres -c 'CREATE TABLE users ( name varchar );'